/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ErrorMessage = string | null;
export type FormatConstraintsFulfilled = boolean;
export type FormatConstraintsExpression = string | null;
export type Hints = string | null;
export type RequirementConstraintsFulfilled = boolean;
export type RequirementIsConditional = boolean;

export interface AhbExpressionEvaluationResultSchema {
  format_constraint_evaluation_result?: {
    error_message?: ErrorMessage;
    format_constraints_fulfilled?: FormatConstraintsFulfilled;
  };
  requirement_constraint_evaluation_result?: {
    format_constraints_expression?: FormatConstraintsExpression;
    hints?: Hints;
    requirement_constraints_fulfilled?: RequirementConstraintsFulfilled;
    requirement_is_conditional?: RequirementIsConditional;
  };
  requirement_indicator?: string;
  [k: string]: unknown;
}
