/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FormatConstraintKeys = string[];
export type HintKeys = string[];
export type PackageKeys = string[];
export type RequirementConstraintKeys = string[];
export type TimeConditionKeys = string[];

/**
 * A Categorized Key Extract contains those condition keys that are contained inside an expression.
 * For expressions (that do not contain any unresolved package) it's possible to pre-generate all possible outcomes of
 * a content evaluation. CategorizedKeyExtract is also the answer to the question:
 * 'Which information do I need to provide in a ContentEvaluationResult in order to evaluate a given expression?'
 */
export interface CategorizedKeyExtract {
  format_constraint_keys?: FormatConstraintKeys;
  hint_keys?: HintKeys;
  package_keys?: PackageKeys;
  requirement_constraint_keys?: RequirementConstraintKeys;
  time_condition_keys?: TimeConditionKeys;
  [k: string]: unknown;
}
