/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConditionKey = string;
export type ConditionText = string | null;
/**
 * existing EDIFACT formats
 */
export type EdifactFormat =
  | "APERAK"
  | "COMDIS"
  | "CONTRL"
  | "IFTSTA"
  | "INSRPT"
  | "INVOIC"
  | "MSCONS"
  | "ORDCHG"
  | "ORDERS"
  | "ORDRSP"
  | "PRICAT"
  | "QUOTES"
  | "REMADV"
  | "REQOTE"
  | "PARTIN"
  | "UTILMD"
  | "UTILMDG"
  | "UTILMDS"
  | "UTILMDW"
  | "UTILTS";

/**
 * maps a condition from a specified EDIFACT format onto a text as it is found in the AHB.
 */
export interface ConditionKeyConditionTextMapping {
  condition_key: ConditionKey;
  condition_text?: ConditionText;
  edifact_format: EdifactFormat;
  [k: string]: unknown;
}
