/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ErrorMessage = string | null;
export type FormatConstraintFulfilled = boolean;

/**
 * This class is the base class of all evaluated format constraints. They are used in the context of the
 * Mussfeldprüfung after the format constraints are evaluated to see if the format constraint expression is
 * fulfilled or not.
 */
export interface EvaluatedFormatConstraint {
  error_message?: ErrorMessage;
  format_constraint_fulfilled: FormatConstraintFulfilled;
  [k: string]: unknown;
}
