/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ErrorMessage = string | null;
export type FormatConstraintFulfilled = boolean;

export interface EvaluatedFormatConstraintSchema {
  error_message?: ErrorMessage;
  format_constraint_fulfilled?: FormatConstraintFulfilled;
  [k: string]: unknown;
}
