/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ErrorMessage = string | null;
export type FormatConstraintsFulfilled = boolean;

/**
 * A class for the result of the format constraint evaluation.
 */
export interface FormatConstraintEvaluationResult {
  error_message?: ErrorMessage;
  format_constraints_fulfilled: FormatConstraintsFulfilled;
  [k: string]: unknown;
}
