/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * existing EDIFACT formats
 */
export type EdifactFormat =
  | "APERAK"
  | "COMDIS"
  | "CONTRL"
  | "IFTSTA"
  | "INSRPT"
  | "INVOIC"
  | "MSCONS"
  | "ORDCHG"
  | "ORDERS"
  | "ORDRSP"
  | "PRICAT"
  | "QUOTES"
  | "REMADV"
  | "REQOTE"
  | "PARTIN"
  | "UTILMD"
  | "UTILMDG"
  | "UTILMDS"
  | "UTILMDW"
  | "UTILTS";
export type PackageExpression = string | null;
export type PackageKey = string;

/**
 * maps a package key from a specified EDIFACT format onto a (not yet parsed) condition expression as it is found in
 * the AHB.
 */
export interface PackageKeyConditionExpressionMapping {
  edifact_format: EdifactFormat;
  package_expression?: PackageExpression;
  package_key: PackageKey;
  [k: string]: unknown;
}
