/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EdifactFormat =
  | "APERAK"
  | "COMDIS"
  | "CONTRL"
  | "IFTSTA"
  | "INSRPT"
  | "INVOIC"
  | "MSCONS"
  | "ORDCHG"
  | "ORDERS"
  | "ORDRSP"
  | "PRICAT"
  | "QUOTES"
  | "REMADV"
  | "REQOTE"
  | "PARTIN"
  | "UTILMD"
  | "UTILMDG"
  | "UTILMDS"
  | "UTILMDW"
  | "UTILTS";
export type PackageExpression = string | null;
export type PackageKey = string;

export interface PackageKeyConditionExpressionMappingSchema {
  edifact_format?: EdifactFormat;
  package_expression?: PackageExpression;
  package_key?: PackageKey;
  [k: string]: unknown;
}
