/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FormatConstraintsExpression = string | null;
export type Hints = string | null;
export type RequirementConstraintsFulfilled = boolean;
export type RequirementIsConditional = boolean;

export interface RequirementConstraintEvaluationResultSchema {
  format_constraints_expression?: FormatConstraintsExpression;
  hints?: Hints;
  requirement_constraints_fulfilled?: RequirementConstraintsFulfilled;
  requirement_is_conditional?: RequirementIsConditional;
  [k: string]: unknown;
}
