/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = boolean & string;
export type Value = string | null;

export interface TokenSchema {
  type?: Type;
  value?: Value;
  [k: string]: unknown;
}
